require File.expand_path('../extensions/net_smtp.rb', File.dirname(__FILE__))
require File.expand_path('../extensions/action_mailer.rb', File.dirname(__FILE__))
require File.expand_path('./mailer.rb', File.dirname(__FILE__))
require File.expand_path('./attendee.rb', File.dirname(__FILE__))
require File.expand_path('./csv_parser.rb', File.dirname(__FILE__))
require File.expand_path('./bulk_processor.rb', File.dirname(__FILE__))
